### ISSUE TITLE
Code generation related to styling childs broken on current master

### ISSUE THREAD

**Issue by plnice** [airbnb/paris#69]
Steps to reproduce:

1. Check out current master (0f6dc69), build packages and use them in your project (I've changed version to `1.1.0-SNAPSHOT` and run `./gradlew clean install` which published them to local maven)
1. Prepare custom View with `@StyleableChild`
1. Add additional style that adds default style and styles child:
```
@Style
val DARK_GREY_STYLE = customViewStyle {
  addDefault()
  customChildStyle(R.style.CustomChildStyle)
}
```
4. Try to build app. `addDefault()` and `customChildStyle()` methods are not found. Additionally when I've inspected generated code of `BaseStyleBuilder` class in `CustomViewStyleApplier.java` the following compilation error was there:
```
Type parameter 'android.widget.TextViewStyleApplier.StyleBuilder' is not within its bound; should extend 'com.airbnb.paris.StyleBuilder<B,A>'
```
related to `function` argument of generated method:
```
public B customChildStyle(StyleBuilderFunction<TextViewStyleApplier.StyleBuilder> function) {
   ...
}
```

The issue is caused by e057241, after reverting this commit and re-publishing Paris packages the issue is not there anymore.

**Comment by ngsilverman** [comment]
@plnice Interesting. This test seems to cover the use case you're describing: https://github.com/airbnb/paris/blob/master/paris/src/testDebug/java/com/airbnb/paris/views/kotlin/WithStyleableChildKotlinViewStyleExtensionsTest.kt#L70

Just to make sure, I tried defining a linked style directly in the corresponding view class using `addDefault` and a child style using a style resource and everything seemed fine. So at this point **I'm not able to reproduce the issue.**

Part of the https://github.com/airbnb/paris/commit/e05724160ca34766c4dbbb52df5d8c1ceec42e2d  change is that functions, like `addDefault` or `customChildStyle` in your example, are now extensions, and need to be imported individually. Make sure your view class has:
```kotlin
import com.airbnb.paris.extensions.addDefault
import com.airbnb.paris.extensions.customChildStyle
```
Or:
```kotlin
import com.airbnb.paris.extensions.*
```

----

The type parameter warning should be inconsequential, Kotlin extensions don't use `BaseStyleBuilder` anymore. Even then, I'm pretty sure that's just a warning with no functional impact (but fixing it would be nice).

----

If this doesn't resolve your issue could you put up a PR adding either a failing test or modifying the sample so that the build fails with the same error? Thanks!

**Comment by plnice** [comment]
OK, the issue was that I didn't import extension functions, thought it was an IDE mistake to suggest to import them :-) After importing them everything works fine.

**Comment by ngsilverman** [comment]
Yay!! Glad it worked out with no changes needed. 😄
